{{- $chartName := include "geocoding-enrichment.name" . -}}
{{- $tracingUrl := include "geocoding-enrichment.tracingUrl" . -}}
{{- $metricsUrl := include "geocoding-enrichment.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  KAFKAJS_NO_PARTITIONER_WARNING: "1"
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  KAFKA_INPUT_TOPIC: {{ .Values.kafkaTopics.input | quote }}
  KAFKA_CONSUMER_GROUP_ID: {{ .Values.kafkaConsumers.groupId | quote }}
  {{- with .Values.kafka }}
  KAFKA_BROKERS: {{ .brokers | quote }}
  {{- if .sslAuth.enabled }}
  KAFKA_ENABLE_SSL_AUTH: "true"
  KAFKA_CA_PATH: {{ .sslAuth.certDir }}/{{ .sslAuth.caFileName }}
  KAFKA_KEY_PATH: {{ .sslAuth.certDir }}/{{ .sslAuth.keyFileName }}
  KAFKA_CERT_PATH: {{ .sslAuth.certDir }}/{{ .sslAuth.certFileName }}
  {{- else }}
  KAFKA_ENABLE_SSL_AUTH: "false"
  {{- end }}
  {{- if .sasl }}
  KAFKA_SASL_MECHANISM: {{ .sasl.mechanism }}
  {{- end }}
  {{- end }}
  USER_DATA_SERVICE_ENDPOINT: {{ .Values.application.userDataService.endpoint | quote }}
  HEADER_PARAMS: {{ .Values.application.userDataService.headers | quote }}
  {{- with .Values.elastic }}
  ELASTIC_URL: {{ .node | quote }}
  ELASTIC_INDEX: {{ .properties.index | quote }}
  {{- end }}
  {{- if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  TELEMETRY_TRACING_RATIO: {{ .Values.env.tracing.ratio | quote }}
  {{- end }}
  {{- if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{- end }}
{{- end }}