{{- $releaseName := .Release.Name -}}
{{- $chartName := include "geocoding-enrichment.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "geocoding-enrichment.environment" . }}
    release: {{ $releaseName }}
    {{- include "geocoding-enrichment.labels" . | nindent 4 }}
data:
{{- if or (ne .Values.elastic.auth.username "") (ne .Values.elastic.auth.password "") }}
  ELASTIC_USERNAME: {{ .Values.elastic.auth.username | b64enc }}
  ELASTIC_PASSWORD: {{ .Values.elastic.auth.password | b64enc }}
{{- end }}
{{- if .Values.kafka.sasl }}
  KAFKA_SASL_USERNAME: {{ .Values.kafka.sasl.username | b64enc }}
  KAFKA_SASL_PASSWORD: {{ .Values.kafka.sasl.password | b64enc }}
{{- end }}
{{- end }}