global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
revisionHistoryLimit: 5
environment: development
initialDelaySeconds: 60
replicaCount: 1

annotations: {}
podAnnotations: {}

pullSecret: pull-secret

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: docker.registry.com/mapcolonies
  imagePullSecretName: pull-secret

image:
  repository: geocoding-enrichment
  pullPolicy: Always
  tag: "v1.4.0"

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
    ratio: 1
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  hashKey:
    enabled: false
    value: hashKeyValue

kafka:
  brokers: broker-1.kafka.com:9092,broker-2.kafka.com:9092,broker-3.kafka.com:9092
  sslAuth:
    enabled: true
    certDir: /tmp/certs/kafka
    secretName: kafka-prep-certs
    certFileName: kafka.pem
    keyFileName: kafka.key
    caFileName: root.crt

kafkaTopics:
  input: |-
    ["feedback-np"]

kafkaConsumers:
  groupId: feedback-consumers-np

elastic:
  node: http://elastic.com
  auth:
    username: elastic
    password: 1234a
  properties:
    index: geocoding_enrichment_np

application:
  userDataService:
    endpoint: https://user-data.com
    headers: |-
      {
        "token": "token1",
        "version": "1.0"
      }

resources:
  enabled: true
  value:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi